//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchivePasswordTestTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchivePasswordTestTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Analyzing archive information... 的本地化字符串。
        /// </summary>
        public static string AnalyzingArchiveInformation {
            get {
                return ResourceManager.GetString("AnalyzingArchiveInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/dawn-lc/ArchivePasswordTestTool 的本地化字符串。
        /// </summary>
        public static string AppHomePage {
            get {
                return ResourceManager.GetString("AppHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ArchivePasswordTestTool 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive file not found. 的本地化字符串。
        /// </summary>
        public static string ArchiveFileNotFound {
            get {
                return ResourceManager.GetString("ArchiveFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive information: Format={0}, File count={1}, Fully encrypted={2}, Supports quick test={3} 的本地化字符串。
        /// </summary>
        public static string ArchiveInformation {
            get {
                return ResourceManager.GetString("ArchiveInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not an encrypted archive. 的本地化字符串。
        /// </summary>
        public static string ArchiveNotEncrypted {
            get {
                return ResourceManager.GetString("ArchiveNotEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dawn-lc 的本地化字符串。
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password dictionary file not found. 的本地化字符串。
        /// </summary>
        public static string DictionaryFileNotFound {
            get {
                return ResourceManager.GetString("DictionaryFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current password dictionary contains {0} passwords. 的本地化字符串。
        /// </summary>
        public static string DictionaryPasswordCount {
            get {
                return ResourceManager.GetString("DictionaryPasswordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: Archive is fully encrypted, quick test cannot be used! 的本地化字符串。
        /// </summary>
        public static string FullyEncryptedArchiveWarning {
            get {
                return ResourceManager.GetString("FullyEncryptedArchiveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found decompression password: {0} 的本地化字符串。
        /// </summary>
        public static string PasswordFoundSuccess {
            get {
                return ResourceManager.GetString("PasswordFoundSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Correct decompression password not found! 的本地化字符串。
        /// </summary>
        public static string PasswordNotFound {
            get {
                return ResourceManager.GetString("PasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to save the test results? 的本地化字符串。
        /// </summary>
        public static string SaveTestResultsPrompt {
            get {
                return ResourceManager.GetString("SaveTestResultsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to initialize 7z.dll: {0} 的本地化字符串。
        /// </summary>
        public static string SevenZipDllInitializationFailed {
            get {
                return ResourceManager.GetString("SevenZipDllInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully loaded 7zip 的本地化字符串。
        /// </summary>
        public static string SevenZipDllLoadedSuccessfully {
            get {
                return ResourceManager.GetString("SevenZipDllLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7z.dll not found: {0}
        ///Please download and install 7-Zip first. 的本地化字符串。
        /// </summary>
        public static string SevenZipDllNotFound {
            get {
                return ResourceManager.GetString("SevenZipDllNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please provide the path to 7z.dll! 的本地化字符串。
        /// </summary>
        public static string SevenZipDllPathRequired {
            get {
                return ResourceManager.GetString("SevenZipDllPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test completed, elapsed time: {0} 的本地化字符串。
        /// </summary>
        public static string TestCompletedWithTime {
            get {
                return ResourceManager.GetString("TestCompletedWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Testing password 的本地化字符串。
        /// </summary>
        public static string TestingPasswordProgress {
            get {
                return ResourceManager.GetString("TestingPasswordProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive: {0} 的本地化字符串。
        /// </summary>
        public static string TestResultArchive {
            get {
                return ResourceManager.GetString("TestResultArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive Hash: {0} 的本地化字符串。
        /// </summary>
        public static string TestResultArchiveHash {
            get {
                return ResourceManager.GetString("TestResultArchiveHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompression password: {0} 的本地化字符串。
        /// </summary>
        public static string TestResultDecompressionPassword {
            get {
                return ResourceManager.GetString("TestResultDecompressionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dictionary: {0} 的本地化字符串。
        /// </summary>
        public static string TestResultDictionary {
            get {
                return ResourceManager.GetString("TestResultDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elapsed time: {0} 的本地化字符串。
        /// </summary>
        public static string TestResultElapsedTime {
            get {
                return ResourceManager.GetString("TestResultElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The correct decompression password was not found! 的本地化字符串。
        /// </summary>
        public static string TestResultPasswordNotFound {
            get {
                return ResourceManager.GetString("TestResultPasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using installed 7-Zip: {0} 的本地化字符串。
        /// </summary>
        public static string UsingInstalledSevenZip {
            get {
                return ResourceManager.GetString("UsingInstalledSevenZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using specified 7z.dll: {0} 的本地化字符串。
        /// </summary>
        public static string UsingSpecifiedSevenZipDll {
            get {
                return ResourceManager.GetString("UsingSpecifiedSevenZipDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to view the test report? 的本地化字符串。
        /// </summary>
        public static string ViewTestReportPrompt {
            get {
                return ResourceManager.GetString("ViewTestReportPrompt", resourceCulture);
            }
        }
    }
}
